apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-logging-config
data:
  logging.properties: |2
    appender.stdout.name = STDOUT
    appender.stdout.type = Console
    rootLogger = info, STDOUT
    logger.activemq.name=org.apache.activemq.artemis.core.config.impl.ConfigurationImpl
    logger.activemq.level=TRACE
    logger.jaas.name=org.apache.activemq.artemis.spi.core.security.jaas
    logger.jaas.level=TRACE
    logger.rest.name=org.apache.activemq.artemis.core
    logger.rest.level=ERROR
---
apiVersion: v1
kind: Secret
metadata:
  name: custom-jaas-config
stringData:
  login.config: |2
    activemq {
      // app specific users and roles	
      org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
       reload=true
       debug=true
       org.apache.activemq.jaas.properties.user="new-users.properties"
       org.apache.activemq.jaas.properties.role="new-roles.properties";

      // ensure the operator can connect to the mgmt console by referencing the existing properties config
      org.apache.activemq.artemis.spi.core.security.jaas.PropertiesLoginModule sufficient
       reload=true
       debug=true
       org.apache.activemq.jaas.properties.user="artemis-users.properties"
       org.apache.activemq.jaas.properties.role="artemis-roles.properties"
       baseDir="/home/jboss/amq-broker/etc";

      };
  new-roles.properties: |-
    admin=pat
    other=joe
    group1=bob
  new-users.properties: |-
    bob=bob
    joe=joe
    pat=pat
---			
apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: artemis-broker
spec:
  deploymentPlan:
    size: 1
    image: placeholder
    extraMounts:
      configMaps:
        - custom-logging-config
      secrets:
        - custom-jaas-config
  brokerProperties:
   - "# rbac"
   - securityRoles.#.admin.send=true
   - securityRoles.#.admin.consume=true
   - securityRoles.#.admin.createNonDurableQueue=true
   - securityRoles.#.admin.deleteNonDurableQueue=true
   - addressConfigurations.demo_address.routingTypes=MULTICAST
   - addressConfigurations.demo_address.queueConfigs.demo_queue1.address=demo_address
   - addressConfigurations.demo_address.queueConfigs.demo_queue1.routingType=MULTICAST
   - addressConfigurations.demo_address.queueConfigs.demo_queue2.address=demo_address
   - addressConfigurations.demo_address.queueConfigs.demo_queue2.routingType=MULTICAST
   - securityRoles.demo_address\:\:demo_queue1.group1.send=true